# -*- coding: utf-8 -*-
"""Using FOR and while.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cXXjbu0Qqte6VoXze1Djoz9yupjHhmsa

EXEMPLE 1
"""

note = averege = sum = 0

print(note, averege ,sum)

for _ in range(1, 6):
  note = float(input('write your note: '))
  sum += note

print(sum)

averege = sum / 5
print(' the averege is', averege)

"""WHILE

"""

number = 1 
while number <= 5:
  note = float(input("write your note: "))
  sum += note
  number += 1
print('the averege is', sum / 5)

"""EXEMPLE 2 """

for i in range(1, 11):
  print('3 x {} = {}'.format(i, 3 * i))

"""WHILE"""

numero = 1
while numero <= 10:
  print('3 x {} = {}'.format(numero, 3 * numero))
  numero += 1